Repository tranquilitybase-io/tb-gcp, pull requests merged in 2020-10, with the labels that each got.

#506 Fixes #502 mv def values from input.tfvars to variables.tf
  tb-gcp-tr/bootstrap/files/bootstrap.sh
  tb-gcp-tr/landingZone/no-itop/input.tfvars
  tb-gcp-tr/landingZone/no-itop/variables.tf
  tb-marketplace/tb-dep-manager/tranquility-base.jinja
Labels: Tech Debt

#507 Fixes #504 cross-project referencing racing condition...
  tb-gcp-tr/shared-bastion/main.tf
Labels: bug

#505 Fixes #503 consolidate bastion & proxy FW rules
  tb-gcp-tr/landingZone/no-itop/main.tf
  tb-gcp-tr/shared-bastion/main.tf
  tb-gcp-tr/shared-bastion/variables.tf
  tb-gcp-tr/shared-vpc/main.tf
Labels: enhancement

#485 Issue 462
  tb-gcp-tr/logging-export/main.tf
Labels: bug

#511 [Refactor] Fixes shared-dac rogue code & syntax
  tb-gcp-tr/shared-dac/eagle_console.yaml
  tb-gcp-tr/shared-dac/jenkins-master.yaml
Labels: Tech Debt

#514 Fixes #510: prevents billing account IAM change fail
  tb-gcp-tools/tb-projects-deleter/tb-projects-deleter
  tb-marketplace/tb-config-creator/tb-config-creator
Labels: bug

#515 Refixes #504: one instance template was missed
  tb-gcp-tr/shared-bastion/main.tf
Labels: bug

#520 Solves #518 allows bastion subnet name change
  tb-gcp-tr/landingZone/no-itop/main.tf
  tb-gcp-tr/landingZone/no-itop/variables.tf
  tb-gcp-tr/shared-bastion/main.tf
  tb-gcp-tr/shared-bastion/variables.tf
  tb-gcp-tr/shared-vpc/main.tf
  tb-gcp-tr/shared-vpc/outputs.tf
  tb-gcp-tr/shared-vpc/variables.tf
Labels: enhancement

#524 Solves #521 & #522: Deploy IAM on net & billing projects
  tb-gcp-tr/landingZone/no-itop/main.tf
  tb-gcp-tr/landingZone/no-itop/variables.tf
  tb-gcp-tr/shared-projects-creation/main.tf
  tb-gcp-tr/shared-projects-creation/variables.tf
Labels: enhancement

#528 Solves #527 bucket_policy_only deprecation warning
  tb-gcp-tr/landingZone/no-itop/main.tf
Labels: Tech Debt, bug

#526 Issue 497
  tb-marketplace/tb-config-creator/tb-config-creator
Labels: enhancement

#530 Solves #525 preserves git history on tb image
  .DS_Store
  .gitignore
  issue-299e
  tb-gcp-deploy/pack/init-no-itop.sh
  tb-gcp-deploy/pack/packer-no-itop.json
  tb-gcp-tr/landingZone/create-private-ingress-gateway.sh
  tb-gcp-tr/landingZone/iap-tunnel.sh
  tb-gcp-tr/landingZone/istio-default-install.sh
  tb-gcp-tr/landingZone/istio-services_new.sh
  tb-gcp-tr/landingZone/kube.sh
  tb-gcp-tr/landingZone/tb-welcome
  tb-test/cloudbuild.yaml
Labels: Tech Debt, enhancement
